### ISSUE TITLE
Add Ahead-of-Time compilation

### ISSUE THREAD

**Issue by jonas99y** [jonas99y/pythagorasvo21#3]
Ahead-of-Time compilation increases performance. Tested with Google [Lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk?hl=de)
[before](https://googlechrome.github.io/lighthouse/viewer/?gist=df69c3e4f302b8d6450ba68b430a1e44)
[after](https://googlechrome.github.io/lighthouse/viewer/?gist=5dda5097df690b48303c624bc9a07b32)

ng build --prod --aot

**Comment by Sirius-A** [comment]
Oh sweet. will modify the CI build

**Comment by Sirius-A** [comment]
Travis now automatically deploys the optimized version to firebase :beers:
